name: Deploy

concurrency: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - id: npmjsVersion
        name: Extract version from package.json
        run: |
          echo "npmjsVersion=`awk '/version/{gsub(/("|",)/,"",$2);print $2};' package.json`" >> $GITHUB_OUTPUT

      - name: Sync production
        run: |
          npm install
          ./node_modules/@markwylde/ftp-deploy/index.js .github/workflows/deployConfig.js
